version: '3.9'

services:
  go-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-parser
    volumes:
      - .:/app
    working_dir: /app
    command: ./go-parser